<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <!-- SCIA-2026: usar siempre el mismo TFM en toda la solución (net8.0 LTS). -->
  </PropertyGroup>
</Project>
