// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sciad.Infrastructure.Persistence;

#nullable disable

namespace Sciad.Infrastructure.Migrations
{
    [DbContext(typeof(SciadDbContext))]
    [Migration("20260830135238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sciad.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_auditoria_fecha");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("ix_auditoria_persona_id");

                    b.ToTable("auditoria", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.CredencialQr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Emitido")
                        .HasColumnType("date")
                        .HasColumnName("emitido");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("activa")
                        .HasColumnName("estado");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<int?>("ReemitidoDe")
                        .HasColumnType("integer")
                        .HasColumnName("reemitido_de");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_credenciales_qr");

                    b.HasIndex("ReemitidoDe")
                        .HasDatabaseName("ix_credenciales_qr_reemitido_de");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_credenciales_qr_token");

                    b.HasIndex("PersonaId", "Estado")
                        .HasDatabaseName("ix_credenciales_qr_persona_id_estado");

                    b.ToTable("credenciales_qr", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_notificaciones");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("ix_notificaciones_persona_id");

                    b.HasIndex("UsuarioId", "Leida")
                        .HasDatabaseName("ix_notificaciones_usuario_id_leida");

                    b.ToTable("notificaciones", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.PerfilAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<DateOnly>("VigenciaFin")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_fin");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer")
                        .HasColumnName("zona_id");

                    b.HasKey("Id")
                        .HasName("pk_perfiles_acceso");

                    b.HasIndex("ZonaId")
                        .HasDatabaseName("ix_perfiles_acceso_zona_id");

                    b.HasIndex("PersonaId", "VigenciaInicio", "VigenciaFin")
                        .HasDatabaseName("ix_perfiles_acceso_persona_id_vigencia_inicio_vigencia_fin");

                    b.ToTable("perfiles_acceso", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DpiCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dpi_codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_personas");

                    b.HasIndex("DpiCodigo")
                        .IsUnique()
                        .HasDatabaseName("ix_personas_dpi_codigo");

                    b.ToTable("personas", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.RegistroAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer")
                        .HasColumnName("zona_id");

                    b.HasKey("Id")
                        .HasName("pk_registros_acceso");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_registros_acceso_usuario_id");

                    b.HasIndex("PersonaId", "Fecha")
                        .HasDatabaseName("ix_registros_acceso_persona_id_fecha");

                    b.HasIndex("Tipo", "Fecha")
                        .HasDatabaseName("ix_registros_acceso_tipo_fecha");

                    b.HasIndex("ZonaId", "Fecha")
                        .HasDatabaseName("ix_registros_acceso_zona_id_fecha");

                    b.HasIndex("PersonaId", "Fecha", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("uq_ingreso_diario")
                        .HasFilter("tipo = 'ingreso'");

                    b.ToTable("registros_acceso", "public", t =>
                        {
                            t.HasCheckConstraint("CK_registros_acceso_tipo", "tipo IN ('ingreso','egreso')");
                        });
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Generado")
                        .HasColumnType("date")
                        .HasColumnName("generado");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("periodo");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("integer")
                        .HasColumnName("total_registros");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_reportes");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_reportes_usuario_id");

                    b.ToTable("reportes", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_codigo");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("puesto");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_usuarios_estado");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol_id");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.ZonaAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NivelSeguridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel_seguridad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_zonas_acceso");

                    b.ToTable("zonas_acceso", "public");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("Sciad.Domain.Entities.Persona", "Persona")
                        .WithMany("Auditorias")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditoria_personas_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.CredencialQr", b =>
                {
                    b.HasOne("Sciad.Domain.Entities.Persona", "Persona")
                        .WithMany("Credenciales")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credenciales_qr_personas_persona_id");

                    b.HasOne("Sciad.Domain.Entities.CredencialQr", "ReemitidaDeCredencial")
                        .WithMany()
                        .HasForeignKey("ReemitidoDe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_credenciales_qr_credenciales_qr_reemitido_de");

                    b.Navigation("Persona");

                    b.Navigation("ReemitidaDeCredencial");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("Sciad.Domain.Entities.Persona", "Persona")
                        .WithMany("Notificaciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificaciones_personas_persona_id");

                    b.HasOne("Sciad.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificaciones_usuarios_usuario_id");

                    b.Navigation("Persona");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.PerfilAcceso", b =>
                {
                    b.HasOne("Sciad.Domain.Entities.Persona", "Persona")
                        .WithMany("Perfiles")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_perfiles_acceso_personas_persona_id");

                    b.HasOne("Sciad.Domain.Entities.ZonaAcceso", "Zona")
                        .WithMany("Perfiles")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_perfiles_acceso_zonas_acceso_zona_id");

                    b.Navigation("Persona");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.RegistroAcceso", b =>
                {
                    b.HasOne("Sciad.Domain.Entities.Persona", "Persona")
                        .WithMany("Registros")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acceso_personas_persona_id");

                    b.HasOne("Sciad.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Registros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acceso_usuarios_usuario_id");

                    b.HasOne("Sciad.Domain.Entities.ZonaAcceso", "Zona")
                        .WithMany("Registros")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acceso_zonas_acceso_zona_id");

                    b.Navigation("Persona");

                    b.Navigation("Usuario");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("Sciad.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reportes_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Sciad.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_rol_id");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Credenciales");

                    b.Navigation("Notificaciones");

                    b.Navigation("Perfiles");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Registros");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("Sciad.Domain.Entities.ZonaAcceso", b =>
                {
                    b.Navigation("Perfiles");

                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
